In [ ]:
!pip install beautifulsoup4 requests pandas

Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
!pip install selenium webdriver-manager
!apt-get update
!apt-get install -y chromium-chromedriver

Requirement already satisfied: selenium in /usr/local/lib/python3.12/dist-packages (4.41.0)
Collecting webdriver-manager
  Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: certifi>=2026.1.4 in /usr/local/lib/python3.12/dist-packages (from selenium) (2026.2.25)
Requirement already satisfied: trio<1.0,>=0.31.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (0.33.0)
Requirement already satisfied: trio-websocket<1.0,>=0.12.2 in /usr/local/lib/python3.12/dist-packages (from selenium) (0.12.2)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (4.15.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (2.6.3)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (1.9.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from webdriver-manager) (2.32.4)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (from webdriver-manager) (1.2.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from webdriver-manager) (26.0)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (25.4.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (3.11)
Requirement already satisfied: outcome in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (1.3.1)
Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.12/dist-packages (from trio-websocket<1.0,>=0.12.2->selenium) (1.3.2)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->webdriver-manager) (3.4.5)
Requirement already satisfied: h11<1,>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl (27 kB)
Installing collected packages: webdriver-manager
Successfully installed webdriver-manager-4.0.2
Hit:1 https://cli.github.com/packages stable InRelease
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:3 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:4 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:7 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:9 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
chromium-chromedriver is already the newest version (1:85.0.4183.83-0ubuntu2.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 137 not upgraded.

Scraping → Dataset → NLP feature extraction → ML model → Salary prediction

(job description + job type + experience + location) → salary

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

In [ ]:
import requests

url = "https://remotive.com/api/remote-jobs"

response = requests.get(url)

data = response.json()

print(data.keys())
print(len(data["jobs"]))

dict_keys(['00-warning', '0-legal-notice', 'job-count', 'total-job-count', 'jobs'])
22

In [ ]:
job = data["jobs"][0]

print(job.keys())

dict_keys(['id', 'url', 'title', 'company_name', 'company_logo', 'category', 'tags', 'job_type', 'publication_date', 'candidate_required_location', 'salary', 'description'])

In [ ]:
print(response.headers["content-type"])
print(response.text[:500])

application/json; charset=utf-8
{"00-warning": "Remotive main domain moved to remotive.com ! Please make your API calls on remotive.com/api/remote-jobs instead of remotive.io now ;) Legacy endpoint remotive.io/api/remote-jobs will be terminated in June 2022. Thank you!", "0-legal-notice": "Legal warning - Hey, thanks for using Remotive's API, we appreciate it! Please note that API documentation and access is granted so that developers can share our jobs further. Please do not submit Remotive jobs to third Party websites, inclu

In [ ]:
data = response.json()

print(type(data))
print(data.keys())

<class 'dict'>
dict_keys(['00-warning', '0-legal-notice', 'job-count', 'total-job-count', 'jobs'])

In [ ]:
print(len(data["jobs"]))

22

API request → JSON response → jobs list (22 entries)

In [ ]:
job = data["jobs"][0]

print(job)

{'id': 2088652, 'url': 'https://remotive.com/remote-jobs/software-development/full-stack-developer-2088652', 'title': 'Full-Stack Developer', 'company_name': 'ELECTE S.R.L.', 'company_logo': 'https://remotive.com/job/2088652/logo', 'category': 'Software Development', 'tags': ['api', 'backend', 'frontend', 'fullstack', 'javascript', 'postgresql', 'python', 'sql', 'AI/ML', 'CI/CD', 'analytics', 'Typescript ', 'SOLID', 'serverless', 'infrastructure', 'github', 'CMS'], 'job_type': 'full_time', 'publication_date': '2026-03-13T15:17:31', 'candidate_required_location': 'Worldwide', 'salary': '$33,6k–$50,4k', 'description': '<p style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); font-weight: 400; line-height: 1.5; color: rgba(0, 0, 0, 0.9);">We are looking for a strong Full-Stack Developer to execute product features and contribute to our core platform development. Your focus will be clean, scalable implementation and high-quality execution. This role is ideal for a developer who enjoys building real product features end-to-end in a focused, no-bureaucracy environment.</p>\n<p style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); font-weight: 400; line-height: 1.5; color: rgba(0, 0, 0, 0.9);"><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;">\xa0</span></p>\n<p style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); font-weight: 400; line-height: 1.5; color: rgba(0, 0, 0, 0.9);"><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;"><strong style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px; font-weight: 600;">Responsibilities</strong></span></p>\n<ul style="">\n<li style="">Implement frontend features using TypeScript</li>\n<li style="">Develop backend services and APIs using Supabase / PostgreSQL</li>\n<li style="">Contribute to our Python-based AI &amp; analytics engine (data logic, integrations)</li>\n<li style="">Write and optimize SQL queries and database logic</li>\n<li style="">Collaborate on feature specifications and translate them into clean technical execution</li>\n<li style="">Participate in code reviews and continuous improvement</li>\n<li style="">Work within modern serverless infrastructure (Vercel / Supabase)</li>\n</ul>\n<p style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); font-weight: 400; line-height: 1.5; color: rgba(0, 0, 0, 0.9);"><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;">\xa0</span></p>\n<p style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); font-weight: 400; line-height: 1.5; color: rgba(0, 0, 0, 0.9);"><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;"><strong style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px; font-weight: 600;">Tech Stack</strong></span></p>\n<ul style="">\n<li style=""><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;"><strong style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px; font-weight: 600;">Core Language:</strong></span> TypeScript</li>\n<li style=""><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;"><strong style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px; font-weight: 600;">Backend &amp; Database:</strong></span> Supabase (PostgreSQL), PL/pgSQL</li>\n<li style=""><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;"><strong style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px; font-weight: 600;">AI Layer:</strong></span> Python</li>\n<li style=""><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;"><strong style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px; font-weight: 600;">Frontend &amp; CMS:</strong></span> TypeScript, Webflow, Weglot API</li>\n<li style=""><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;"><strong style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px; font-weight: 600;">Infrastructure:</strong></span> Vercel / Netlify</li>\n<li style=""><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;"><strong style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px; font-weight: 600;">CI/CD:</strong></span> GitHub Actions</li>\n</ul>\n<p style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); font-weight: 400; line-height: 1.5; color: rgba(0, 0, 0, 0.9);"><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;">\xa0</span></p>\n<p style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); font-weight: 400; line-height: 1.5; color: rgba(0, 0, 0, 0.9);"><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;"><strong style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px; font-weight: 600;">Requirements</strong></span></p>\n<p style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); font-weight: 400; line-height: 1.5; color: rgba(0, 0, 0, 0.9);"><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;"><strong style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px; font-weight: 600;">Must-have:</strong></span></p>\n<ul style="">\n<li style="">Experience as a Full-Stack Developer (3+ years)</li>\n<li style="">Strong knowledge of TypeScript / JavaScript</li>\n<li style="">Solid experience with Python in backend, data, or analytics contexts</li>\n<li style="">Good understanding of PostgreSQL and data modeling</li>\n<li style="">Experience building and consuming APIs</li>\n<li style="">Ability to work independently and deliver clean production-ready code</li>\n</ul>\n<p style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); font-weight: 400; line-height: 1.5; color: rgba(0, 0, 0, 0.9);"><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;">\xa0</span></p>\n<p style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); font-weight: 400; line-height: 1.5; color: rgba(0, 0, 0, 0.9);"><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;"><strong style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px; font-weight: 600;">Nice-to-have:</strong></span></p>\n<ul style="">\n<li style="">Experience with analytics or AI-adjacent systems</li>\n<li style="">Hands-on experience with Supabase</li>\n<li style="">Knowledge of PL/pgSQL</li>\n<li style="">Experience using Webflow</li>\n</ul>\n<p style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); font-weight: 400; line-height: 1.5; color: rgba(0, 0, 0, 0.9);"><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;">\xa0</span></p>\n<p style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); font-weight: 400; line-height: 1.5; color: rgba(0, 0, 0, 0.9);"><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;"><strong style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px; font-weight: 600;">What we offer</strong></span></p>\n<p>\xa0</p>\n<ul style="">\n<li style="">€2,500–3,500/month (contractor)</li>\n<li style="">Full-time</li>\n<li style="">Remote-friendly</li>\n<li style="">Clear technical leadership and structured roadmap</li>\n<li style="">Small team, fast decision-making, no bureaucracy</li>\n</ul>\n<img src="https://remotive.com/job/track/2088652/blank.gif?source=public_api" alt=""/>'}

In [ ]:
import pandas as pd

dataset = []

for job in data["jobs"]:

    dataset.append({
        "title": job["title"],
        "company": job["company_name"],
        "category": job["category"],
        "job_type": job["job_type"],
        "location": job["candidate_required_location"],
        "salary": job["salary"],
        "description": job["description"],
        "tags": job["tags"]
    })

df = pd.DataFrame(dataset)

df.head()

,title,company,category,job_type,location,salary,description,tags
0,Full-Stack Developer,ELECTE S.R.L.,Software Development,full_time,Worldwide,"$33,6k–$50,4k","<p style=""box-sizing: inherit; margin: 0px; pa...","[api, backend, frontend, fullstack, javascript..."
1,Sr. Firmware Engineer,Sanctuary Computer,Software Development,contract,Worldwide,$150k - $200k,"<p style=""--tw-border-spacing-x: 0; --tw-borde...","[AWS, C, C++, cloud, UI/UX, open source, produ..."
2,Audio AI Trainer,Anuttacon,AI / ML,contract,Worldwide,$25/hour,"<p style=""--tw-border-spacing-x: 0; --tw-borde...","[video, AI/ML, research, game design, data ana..."
3,Office Assistant,Coalition Technologies,Marketing,full_time,Worldwide,"$31,2k- $52k","<p class=""h3"">WHY YOU SHOULD APPLY:</p>\n<p> <...","[CSS, excel, frontend, git, html, illustrator,..."
4,iOS Developer,nooro,Software Development,full_time,USA,$60k-$130k (depending on experience),"<p style=""box-sizing: inherit; margin: var(--a...","[api, backend, git, ios, security, swift, UI/U..."

In [ ]:

df.shape

(22, 8)

In [ ]:
df.isnull().sum()

title          0
company        0
category       0
job_type       0
location       0
salary         0
description    0
tags           0
dtype: int64

In [ ]:
df["salary"]

0                            $33,6k–$50,4k
1                            $150k - $200k
2                                 $25/hour
3                             $31,2k- $52k
4     $60k-$130k (depending on experience)
5                          OTE $25k - $35k
6                              $48k - $60k
7                            $50-$75 /hour
8                               $14.5/hour
9                             $80k - $120k
10
11                            €30k -  €60k
12                              $20k -$35k
13                         $220k-$300k OTE
14
15                             $65K - $80K
16                               $50K-$60K
17
18                           $130k - $150k
19
20                       $120 - $170 /hour
21                        $90 - $150 /hour
Name: salary, dtype: object

In [ ]:
df["description"][0]

'<p style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); font-weight: 400; line-height: 1.5; color: rgba(0, 0, 0, 0.9);">We are looking for a strong Full-Stack Developer to execute product features and contribute to our core platform development. Your focus will be clean, scalable implementation and high-quality execution. This role is ideal for a developer who enjoys building real product features end-to-end in a focused, no-bureaucracy environment.</p>\n<p style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); font-weight: 400; line-height: 1.5; color: rgba(0, 0, 0, 0.9);"><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;">\xa0</span></p>\n<p style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); font-weight: 400; line-height: 1.5; color: rgba(0, 0, 0, 0.9);"><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;"><strong style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px; font-weight: 600;">Responsibilities</strong></span></p>\n<ul style="">\n<li style="">Implement frontend features using TypeScript</li>\n<li style="">Develop backend services and APIs using Supabase / PostgreSQL</li>\n<li style="">Contribute to our Python-based AI &amp; analytics engine (data logic, integrations)</li>\n<li style="">Write and optimize SQL queries and database logic</li>\n<li style="">Collaborate on feature specifications and translate them into clean technical execution</li>\n<li style="">Participate in code reviews and continuous improvement</li>\n<li style="">Work within modern serverless infrastructure (Vercel / Supabase)</li>\n</ul>\n<p style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); font-weight: 400; line-height: 1.5; color: rgba(0, 0, 0, 0.9);"><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;">\xa0</span></p>\n<p style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); font-weight: 400; line-height: 1.5; color: rgba(0, 0, 0, 0.9);"><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;"><strong style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px; font-weight: 600;">Tech Stack</strong></span></p>\n<ul style="">\n<li style=""><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;"><strong style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px; font-weight: 600;">Core Language:</strong></span> TypeScript</li>\n<li style=""><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;"><strong style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px; font-weight: 600;">Backend &amp; Database:</strong></span> Supabase (PostgreSQL), PL/pgSQL</li>\n<li style=""><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;"><strong style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px; font-weight: 600;">AI Layer:</strong></span> Python</li>\n<li style=""><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;"><strong style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px; font-weight: 600;">Frontend &amp; CMS:</strong></span> TypeScript, Webflow, Weglot API</li>\n<li style=""><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;"><strong style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px; font-weight: 600;">Infrastructure:</strong></span> Vercel / Netlify</li>\n<li style=""><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;"><strong style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px; font-weight: 600;">CI/CD:</strong></span> GitHub Actions</li>\n</ul>\n<p style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); font-weight: 400; line-height: 1.5; color: rgba(0, 0, 0, 0.9);"><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;">\xa0</span></p>\n<p style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); font-weight: 400; line-height: 1.5; color: rgba(0, 0, 0, 0.9);"><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;"><strong style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px; font-weight: 600;">Requirements</strong></span></p>\n<p style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); font-weight: 400; line-height: 1.5; color: rgba(0, 0, 0, 0.9);"><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;"><strong style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px; font-weight: 600;">Must-have:</strong></span></p>\n<ul style="">\n<li style="">Experience as a Full-Stack Developer (3+ years)</li>\n<li style="">Strong knowledge of TypeScript / JavaScript</li>\n<li style="">Solid experience with Python in backend, data, or analytics contexts</li>\n<li style="">Good understanding of PostgreSQL and data modeling</li>\n<li style="">Experience building and consuming APIs</li>\n<li style="">Ability to work independently and deliver clean production-ready code</li>\n</ul>\n<p style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); font-weight: 400; line-height: 1.5; color: rgba(0, 0, 0, 0.9);"><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;">\xa0</span></p>\n<p style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); font-weight: 400; line-height: 1.5; color: rgba(0, 0, 0, 0.9);"><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;"><strong style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px; font-weight: 600;">Nice-to-have:</strong></span></p>\n<ul style="">\n<li style="">Experience with analytics or AI-adjacent systems</li>\n<li style="">Hands-on experience with Supabase</li>\n<li style="">Knowledge of PL/pgSQL</li>\n<li style="">Experience using Webflow</li>\n</ul>\n<p style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); font-weight: 400; line-height: 1.5; color: rgba(0, 0, 0, 0.9);"><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;">\xa0</span></p>\n<p style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); font-weight: 400; line-height: 1.5; color: rgba(0, 0, 0, 0.9);"><span style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px;"><strong style="box-sizing: inherit; margin: 0px; padding: 0px; border-color: rgba(0, 0, 0, 0.9); border-style: none; border-width: 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: baseline; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); outline: rgba(0, 0, 0, 0.9) none 0px; font-weight: 600;">What we offer</strong></span></p>\n<p>\xa0</p>\n<ul style="">\n<li style="">€2,500–3,500/month (contractor)</li>\n<li style="">Full-time</li>\n<li style="">Remote-friendly</li>\n<li style="">Clear technical leadership and structured roadmap</li>\n<li style="">Small team, fast decision-making, no bureaucracy</li>\n</ul>\n<img src="https://remotive.com/job/track/2088652/blank.gif?source=public_api" alt=""/>'

In [ ]:
df = df[df["salary"] != ""]
df = df[df["salary"].notna()]

print(len(df))

18

In [ ]:
import requests
import pandas as pd

url = "https://remotive.com/api/remote-jobs"

response = requests.get(url)
data = response.json()

jobs = data["jobs"]

df = pd.DataFrame(jobs)

print("Total jobs:", len(df))
df.head()

Total jobs: 22

,id,url,title,company_name,company_logo,category,tags,job_type,publication_date,candidate_required_location,salary,description,company_logo_url
0,2088652,https://remotive.com/remote-jobs/software-deve...,Full-Stack Developer,ELECTE S.R.L.,https://remotive.com/job/2088652/logo,Software Development,"[api, backend, frontend, fullstack, javascript...",full_time,2026-03-13T15:17:31,Worldwide,"$33,6k–$50,4k","<p style=""box-sizing: inherit; margin: 0px; pa...",NaN
1,2088653,https://remotive.com/remote-jobs/software-deve...,Sr. Firmware Engineer,Sanctuary Computer,https://remotive.com/job/2088653/logo,Software Development,"[AWS, C, C++, cloud, UI/UX, open source, produ...",contract,2026-03-13T15:14:23,Worldwide,$150k - $200k,"<p style=""--tw-border-spacing-x: 0; --tw-borde...",https://remotive.com/job/2088653/logo
2,2087694,https://remotive.com/remote-jobs/ai-ml/audio-a...,Audio AI Trainer,Anuttacon,https://remotive.com/job/2087694/logo,AI / ML,"[video, AI/ML, research, game design, data ana...",contract,2026-03-12T21:00:56,Worldwide,$25/hour,"<p style=""--tw-border-spacing-x: 0; --tw-borde...",NaN
3,1680495,https://remotive.com/remote-jobs/marketing/off...,Office Assistant,Coalition Technologies,https://remotive.com/job/1680495/logo,Marketing,"[CSS, excel, frontend, git, html, illustrator,...",full_time,2026-03-11T20:31:07,Worldwide,"$31,2k- $52k","<p class=""h3"">WHY YOU SHOULD APPLY:</p>\n<p> <...",https://remotive.com/job/1680495/logo
4,1956455,https://remotive.com/remote-jobs/software-deve...,iOS Developer,nooro,https://remotive.com/job/1956455/logo,Software Development,"[api, backend, git, ios, security, swift, UI/U...",full_time,2026-03-09T21:16:10,USA,$60k-$130k (depending on experience),"<p style=""box-sizing: inherit; margin: var(--a...",NaN

In [3]:
df = pd.read_csv('/content/Cleaned_DS_Jobs.csv')

In [4]:
df.head(5)

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Type of ownership,Industry,...,company_age,python,excel,hadoop,spark,aws,tableau,big_data,job_simp,seniority
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,Nonprofit Organization,Insurance Carriers,...,27,0,0,0,0,1,0,0,data scientist,senior
1,Data Scientist,137-171,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,Company - Public,Research & Development,...,52,0,0,1,0,0,0,1,data scientist,na
2,Data Scientist,137-171,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,Private Practice / Firm,Consulting,...,39,1,1,0,0,1,0,0,data scientist,na
3,Data Scientist,137-171,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,Company - Public,Electrical & Electronic Manufacturing,...,20,1,1,0,0,1,0,0,data scientist,na
4,Data Scientist,137-171,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,Company - Private,Advertising & Marketing,...,22,1,1,0,0,0,0,0,data scientist,na

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 660 entries, 0 to 659
Data columns (total 28 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Job Title          660 non-null    object
 1   Salary Estimate    660 non-null    object
 2   Job Description    660 non-null    object
 3   Rating             660 non-null    float64
 4   Company Name       660 non-null    object
 5   Location           660 non-null    object
 6   Headquarters       660 non-null    object
 7   Size               660 non-null    object
 8   Type of ownership  660 non-null    object
 9   Industry           660 non-null    object
 10  Sector             660 non-null    object
 11  Revenue            660 non-null    object
 12  min_salary         660 non-null    int64
 13  max_salary         660 non-null    int64
 14  avg_salary         660 non-null    int64
 15  job_state          660 non-null    object
 16  same_state         660 non-null    int64
 17  company_age        660 non-null    int64
 18  python             660 non-null    int64
 19  excel              660 non-null    int64
 20  hadoop             660 non-null    int64
 21  spark              660 non-null    int64
 22  aws                660 non-null    int64
 23  tableau            660 non-null    int64
 24  big_data           660 non-null    int64
 25  job_simp           660 non-null    object
 26  seniority          660 non-null    object
 27  salary_clean       660 non-null    float64
dtypes: float64(2), int64(12), object(14)
memory usage: 144.5+ KB

In [5]:
df['Job Description']

0      Description\n\nThe Senior Data Scientist is re...
1      Secure our Nation, Ignite your Future\n\nJoin ...
2      Overview\n\n\nAnalysis Group is one of the lar...
3      JOB DESCRIPTION:\n\nDo you have a passion for ...
4      Data Scientist\nAffinity Solutions / Marketing...
                             ...
655    Summary\n\nWe’re looking for a data scientist ...
656    Job Description\nBecome a thought leader withi...
657    Join a thriving company that is changing the w...
658    100 Remote Opportunity As an AINLP Data Scient...
659    Description\n\nThe Data Scientist will be part...
Name: Job Description, Length: 660, dtype: object

In [6]:
df['Salary Estimate']

0      137-171
1      137-171
2      137-171
3      137-171
4      137-171
         ...
655    105-167
656    105-167
657    105-167
658    105-167
659    105-167
Name: Salary Estimate, Length: 660, dtype: object

Preprocessing

In [7]:
def convert_salary(s):
    try:
        min_sal, max_sal = s.split("-")
        min_sal = float(min_sal)
        max_sal = float(max_sal)
        return ((min_sal + max_sal) / 2) * 1000
    except:
        return None

df["salary_clean"] = df["Salary Estimate"].apply(convert_salary)

df[["Salary Estimate", "salary_clean"]].head()

  Salary Estimate  salary_clean
0        137-171       154000.0
1        137-171       154000.0
2        137-171       154000.0
3        137-171       154000.0
4        137-171       154000.0

In [8]:
df = df[df["salary_clean"].notna()]
print(len(df))

660

Cleaning the text

In [10]:
import re

def clean_text(text):
    text = str(text)
    text = re.sub(r"<.*?>", "", text)   # remove HTML tags
    text = re.sub(r"[^a-zA-Z]", " ", text)  # keep only alphabets
    text = text.lower()
    return text

df["clean_description"] = df["Job Description"].apply(clean_text)

df["clean_description"].head()

0    description  the senior data scientist is resp...
1    secure our nation  ignite your future  join th...
2    overview   analysis group is one of the larges...
3    job description   do you have a passion for da...
4    data scientist affinity solutions   marketing ...
Name: clean_description, dtype: object

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=5000,
    stop_words="english"
)

X_text = tfidf.fit_transform(df["clean_description"])

In [15]:
df["clean_description"].head()
X_text.shape

(660, 5000)

In [12]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["Location_enc"] = le.fit_transform(df["Location"])
df["Size_enc"] = le.fit_transform(df["Size"])
df["seniority_enc"] = le.fit_transform(df["seniority"])
df["JobTitle_enc"] = le.fit_transform(df["Job Title"])

In [13]:
import numpy as np
from scipy.sparse import hstack

X = hstack([
    X_text,
    np.array(df[["Location_enc", "Size_enc", "seniority_enc", "JobTitle_enc"]])
])

y = df["salary_clean"]

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = RandomForestRegressor()
model.fit(X_train, y_train)

RandomForestRegressor()

In [16]:
from sklearn.metrics import mean_absolute_error

preds = model.predict(X_test)

print("MAE:", mean_absolute_error(y_test, preds))

MAE: 33437.311848548314

ML Pipeline

In [17]:
import pandas as pd
import numpy as np
import re

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestRegressor

In [18]:
def convert_salary(s):
    try:
        min_sal, max_sal = s.split("-")
        return ((float(min_sal) + float(max_sal)) / 2) * 1000
    except:
        return None

df["salary_clean"] = df["Salary Estimate"].apply(convert_salary)

df = df[df["salary_clean"].notna()]

In [19]:
def clean_text(text):
    text = str(text)
    text = re.sub(r"<.*?>", "", text)
    text = re.sub(r"[^a-zA-Z]", " ", text)
    return text.lower()

df["clean_description"] = df["Job Description"].apply(clean_text)

In [20]:
text_feature = "clean_description"

categorical_features = [
    "Location",
    "Size",
    "seniority",
    "Job Title"
]

X = df[[text_feature] + categorical_features]
y = df["salary_clean"]

In [21]:
preprocessor = ColumnTransformer(
    transformers=[
        ("text", TfidfVectorizer(max_features=5000, stop_words="english"), text_feature),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ]
)

In [22]:
pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(n_estimators=100, random_state=42))
])

In [23]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('text',
                                                  TfidfVectorizer(max_features=5000,
                                                                  stop_words='english'),
                                                  'clean_description'),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Location', 'Size',
                                                   'seniority',
                                                   'Job Title'])])),
                ('model', RandomForestRegressor(random_state=42))])

In [24]:
from sklearn.metrics import mean_absolute_error

preds = pipeline.predict(X_test)

print("MAE:", mean_absolute_error(y_test, preds))

MAE: 33643.35202436097

In [25]:
new_data = pd.DataFrame([{
    "clean_description": clean_text("Looking for a data scientist with Python and machine learning experience"),
    "Location": "New York, NY",
    "Size": "1001 to 5000 employees",
    "seniority": "senior",
    "Job Title": "Data Scientist"
}])

prediction = pipeline.predict(new_data)

print("Predicted Salary:", prediction[0])

Predicted Salary: 109379.58333333331

In [26]:
import joblib

joblib.dump(pipeline, "salary_model.pkl")

['salary_model.pkl']

In [27]:
import joblib

joblib.dump(pipeline, "salary_model.pkl")

['salary_model.pkl']

In [30]:
test1 = pd.DataFrame([{
    "clean_description": clean_text("Python ML engineer"),
    "Location": "New York, NY",
    "Size": "51 to 200 employees",
    "seniority": "junior",
    "Job Title": "Data Scientist"
}])

test2 = pd.DataFrame([{
    "clean_description": clean_text("Python ML engineer"),
    "Location": "New York, NY",
    "Size": "10000+ employees",
    "seniority": "senior",
    "Job Title": "Data Scientist"
}])

print(pipeline.predict(test1))
print(pipeline.predict(test2))

[114006.25]
[114151.25]